### ISSUE TITLE
How to make nglview view object dump PNG file

### ISSUE THREAD

**Issue by scottwsides** [nglviewer/nglview#928] opened 2020-10-28 19:31 UTC
The view.download_image and view.render_image() methods are not working. No file is produced and there's an empty image in the 2nd case. I see lots of tickets about this... but they seem old or the latest ones have suggestions that do not work. Is there some other procedure?

**Comment by hainm** [comment] 2020-10-28 19:32
Did you display the view first?

**Comment by scottwsides** [comment] 2020-10-28 20:14
I'm not sure what you mean by 'display it'. The correct image has been displayed in the JupyterLab session

**Comment by hainm** [comment] 2020-10-28 20:20
@scottwsides Can you reproduce this example? https://user-images.githubusercontent.com/4451957/58068981-a1e9a980-7b61-11e9-9d87-d31bdf77822f.png

**Comment by scottwsides** [comment] 2020-10-28 20:27
The demo image is there but the render_image is not

<img width="932" alt="Screen Shot 2020-10-28 at 2 27 06 PM" src="https://user-images.githubusercontent.com/13578795/97492828-b969bc00-1929-11eb-839d-4745ec55561d.png">

**Comment by hainm** [comment] 2020-10-28 20:33
uhm, I am not sure. Works fine with jupyterlab ` 2.2.8`.

<img width="1287" alt="Screen Shot 2020-10-28 at 4 32 31 PM" src="https://user-images.githubusercontent.com/4451957/97493371-3d786f80-193b-11eb-9950-5f026a0d6762.png">

**Comment by scottwsides** [comment] 2020-10-28 20:37
I've got 
JupyterLab 2.1.0
nglview 2.7.7

**Comment by hainm** [comment] 2020-10-28 20:38
You can try with traditional notebook first to see if that's jupyterlab's issue.

**Comment by hainm** [comment] 2020-11-04 04:33
> You can try with traditional notebook first to see if that's jupyterlab's issue.

@scottwsides Any luck?

**Comment by scottwsides** [comment] 2020-11-04 16:52
Not yet. Some other issues not related to this came up and I've got deadlines. but I will try this out. I'lll try jupyterlab 2.2.0 to start with.

**Comment by jochym** [comment] 2021-02-01 10:38
I have similar issues. Linux machines, JL 2.2.9. I can reproduce the demo fine but with a small quirk - maybe it  is a clue. At first moment it shows a broken icon - presumably empty file and after a short while (1s or so) it updates and shows the final correct image. The issue is that if I do  render / _display_image pair to get image data it randomly saves empty or old data. I need to rerun it several times to get a proper picture. The download_image seems to work. Unfortunately there is no get_mage function the render_image source talks about.

I suspect the issue is rather documentation-related, so here is my direct question:
What is a correct way to get image data to your script (*not* trigger image download to your browser - this works)?

**Comment by hainm** [comment] 2021-02-01 16:41
hi @jochym 
> At first moment it shows a broken icon - presumably empty file and after a short while (1s or so) it updates and shows the final correct image. 

The broken icon is an `ipywidgets.Image` object that is waiting the image data from JS code in browser. 

> What is a correct way to get image data to your script 

You have to run your script in another Thread to wait for the image data (via time.sleep). Using different thread to avoid blocking the notebook code (You can try running it in the main thread to see what I meant). 

Here is the example:
```python
import time

def process_images():
    view.clear()
    view.add_cartoon(color='red')
    im0 = view.render_image()
    view.clear()
    view.add_cartoon(color='blue')
    im1 = view.render_image()
    for im in [im0, im1]:
        while not im.value:
            time.sleep(0.1)
    with open('abc0.png', 'wb') as fh:
        fh.write(im0.value)
    with open('abc1.png', 'wb') as fh:
        fh.write(im1.value)

import threading
thread = threading.Thread(
    target=process_images,
)
thread.daemon = True
thread.start()
```

**Comment by jochym** [comment] 2021-02-01 19:03
That is what I suspected  - thanks for the example. It works well. May I suggest adding this to the docs before closing the issue?

**Comment by hainm** [comment] 2021-02-01 19:43
>  May I suggest adding this to the docs before closing the issue?

yeah, would you mind submitting a PR?

**Comment by jochym** [comment] 2021-02-03 12:10
I'll try to get to it soon. Where should I put this info (which file)?

**Comment by hainm** [comment] 2021-02-03 15:41
@jochym  You might put the info here in Q&A: https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md
Thanks

**Comment by jochym** [comment] 2021-02-05 15:48
Done: https://github.com/nglviewer/nglview/pull/945

**Closed** 2021-08-13 20:27 UTC
